// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type GetTlsReq struct {
	Domains []string `form:"domains"`
}

type GetTlsResp struct {
	Domain            string `json:"domain"`
	CertURL           string `json:"certUrl"`
	CertStableURL     string `json:"certStableUrl"`
	PrivateKey        []byte `json:"privateKey"`
	Certificate       []byte `json:"certificate"`
	IssuerCertificate []byte `json:"issuerCertificate"`
	CSR               []byte `json:"cSR"`
}

type PostCreateTlsReq struct {
	Domains      []string          `json:"domains"`
	DnsChallenge string            `json:"dnsChallenge"`
	DnsConfig    map[string]string `json:"dnsConfig"`
}

type PostCreateTlsResp struct {
	Domain            string `json:"domain"`
	CertURL           string `json:"certUrl"`
	CertStableURL     string `json:"certStableUrl"`
	PrivateKey        []byte `json:"privateKey"`
	Certificate       []byte `json:"certificate"`
	IssuerCertificate []byte `json:"issuerCertificate"`
	CSR               []byte `json:"cSR"`
}
