// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type Request struct {
	Domain string `path:"domain"`
}

type Response struct {
	Domain            string `json:"domain"`
	CertURL           string `json:"certUrl"`
	CertStableURL     string `json:"certStableUrl"`
	PrivateKey        []byte `json:"privateKey"`
	Certificate       []byte `json:"certificate"`
	IssuerCertificate  []byte `json:"issuerCertificate"`
	CSR                []byte `json:"cSR"`
}
