// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"esay-tls-server/cmd/tls/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create/tls",
				Handler: createTlsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/get/tls",
				Handler: getTlsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/registered/lets/encrypt",
				Handler: registeredLetsEncryptHandler(serverCtx),
			},
		},
		rest.WithSignature(serverCtx.Config.Signature),
		rest.WithPrefix("/v1"),
	)
}
